
spring:
  # DB
  datasource:
    driver-class-name: org.h2.Driver
    username: kong
    password: kong
    url: jdbc:h2:file:C:/h2Data/240910
    #url: jdbc:h2:mem:testdb;MODE=MySQL #MySQL호환

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    #defer-datasource-initialization: true

  # H2
  h2:
    console:
      enabled: true

  # logging
  logging:
    level:
      root: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicTypeDescriptor: TRACE
      org.springframework.data: DEBUG

  # Batch
  batch:
    #jdbc:
      #initialize-schema: always
    job:
      enabled: false

  # Batch Test
  task:
    scheduling:
      enabled: false
